### ISSUE TITLE
Postfix container crashes

### ISSUE THREAD

**Issue by lenando8** [tgiesela/mailserver#2]
Postfix crashes and gets restarted all the time

The log shows
postmap: fatal: bad string length 0 < 1: mydomain =

imho it complains, that mydomain is needed but empty. 
I didn´t find a way to set mydomain. I wrote a line in the yml script like:

command: /usr/sbin/postconf -e mydomain=myowndomain.my

for some reason postconf only dumped the settings of postfix, all were default values.
 
 
 Thanks

**Comment by tgiesela** [comment]
Thanks for your comment. The issue was in the docker-compose.xml.example file. It was missing the line  - EMAILDOMAIN=<yourdomain>. I updated the example file.

**Comment by lenando8** [comment]
Many Thanks!!

That solved the problem!

Greetings Andreas

---

Diese Nachricht ist vertraulich, oder auch nicht. Sollten Sie nicht der
rechtmäßige Empfänger sein, so nehmen Sie bitte zur Kenntnis, daß der
Absender ein merkbefreiter Trottel ist, der vertrauliche Informationen
unverschlüsselt durchs Netz jagt. GPG Schlüssel verfügbar!
